### ISSUE TITLE
Generating bug

### ISSUE THREAD

**Issue by Marcuri02** [dfsek/BetterEnd-Public#36]
**Describe the bug**

Generating bug

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions**
Please submit the output of the following commands:
`/paper version` (or `/spigot version`)
`/be version`
**Do not submit just the version number, submit the entire command output!**

**Additional context**

[09:29:23 INFO]: [BetterEnd] Generating structure "end_tower",  at 1734.0, 64.0, -695.0. Dimensions: X: 15, Y: 14, Z: 15
[09:29:23 WARN]: java.lang.IllegalArgumentException: Enchantment level is either too low or too high (given 1, bounds are 0 to 0)
[09:29:23 WARN]:        at org.bukkit.inventory.ItemStack.addEnchantment(ItemStack.java:395)
[09:29:23 WARN]:        at com.dfsek.betterend.structures.LootTable.randomEnchantment(LootTable.java:199)
[09:29:23 WARN]:        at com.dfsek.betterend.structures.LootTable.populateChest(LootTable.java:125)
[09:29:23 WARN]:        at com.dfsek.betterend.populators.StructurePopulator.fillInventories(StructurePopulator.java:212)
[09:29:23 WARN]:        at com.dfsek.betterend.populators.StructurePopulator.populate(StructurePopulator.java:131)
[09:29:23 WARN]:        at net.minecraft.server.v1_15_R1.Chunk.loadCallback(Chunk.java:875)
[09:29:23 WARN]:        at net.minecraft.server.v1_15_R1.PlayerChunk.lambda$null$13(PlayerChunk.java:756)
[09:29:23 WARN]:        at net.minecraft.server.v1_15_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:145)
[09:29:23 WARN]:        at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1088)
[09:29:23 WARN]:        at net.minecraft.server.v1_15_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:615)
[09:29:23 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106)
[09:29:23 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1090)
[09:29:23 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[09:29:23 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1164)
[09:29:23 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962)
[09:29:23 WARN]:        at java.lang.Thread.run(Thread.java:748)
[09:29:23 INFO]: [BetterEnd] Invalid item "iron_pickaxe"

**Comment by dfsek** [comment]
Please follow the proper format when submitting issues. Either edit and reopen this issue, or submit a new issue following the format.
